Visualizer: Show number of blocks at the top level
Traverse-Research/gpu-allocator pull request #33
Opened 2021-06-10 09:34 UTC by hrydgard

Lets you waste less time expanding Types that don't have anything in them:

![image](https://user-images.githubusercontent.com/130929/121501710-c4b4b800-c9df-11eb-9b6c-c2e78f3bd3c8.png)

Alternatively I guess you could entirely hide such Types.

2021-06-10 09:35 UTC, Jasper-Bekkers approved these changes

2021-06-10 09:39 UTC, MarijnS95 approved these changes
Definitely!

On mobile it looks like there's a trailing space in the call, the CI will probably fail on that in fmt.

2021-06-10 09:45 UTC, max-traverse commented
This may conflict with ImGUI's label based state tracking. I suspect it will automatically close the collapsing header when the number of blocks change. I know of using `some_hidden_name##visible name` to avoid ID conflicts, but I don't know on top of my head if there is a way to specify an ID that is not linked to the label.
I'll try to find some time today to double check this, as I do think this is a good feature.

2021-06-10 10:03 UTC, max-traverse requested changes
Ah I found the issue with a solution in this github issue: https://github.com/ocornut/imgui/issues/1481
If you could apply the same fix here I think it's ready for merging.

2021-06-10 11:26 UTC, hrydgard commented
Not sure exactly which solution in that thread you're referring to? Seems all over the place to me.

2021-06-10 11:33 UTC, hrydgard commented
I implemented what looks like the simplest solution - hope that's what you meant.

2021-06-10 11:38 UTC, MarijnS95 commented
@hrydgard It appears @max-traverse is referring to the tree posts from the author of ImGUI: https://github.com/ocornut/imgui/issues/1481#issuecomment-349718791. Supposedly `TreeNode` should be used over `CollapsingHeader` as the latter one is "not an API designed for that sort of data" (third comment), the second comment shows how to implement that.

2021-06-10 11:42 UTC, hrydgard commented
Yeah, in C++.

That's a bit of a bigger change than I have time for, and what I implemented works fine.

2021-06-10 11:48 UTC, MarijnS95 commented
@hrydgard And it's 2017, too. I cannot even find the bindings for most of the functions, let alone those sys bindings being used by the high-level wrapper. Fine by me to leave it as-is, unless Max sees a different way forward.

2021-06-10 14:03 UTC, max-traverse commented
I was talking about the `###`. Could you check if increasing/decreasing the number of blocks doesn't open/close the header?

2021-06-10 15:10 UTC, hrydgard commented
Right, but that's not what you linked to.

Either way, I do use ### here and it works as expected.

2021-06-11 08:46 UTC, hrydgard commented
Can we get this merged? I've tested, it works.

2021-06-11 10:07 UTC, max-traverse commented
It looks good to me! Let's merge it in. Thank you for your contribution ^.^

2021-06-11 10:08 UTC, max-traverse approved these changes

2021-06-11 10:08 UTC, merged