Add d3d12 support to gpu-allocator
Traverse-Research/gpu-allocator pull request #41
Opened 2021-08-16 07:43 UTC by max-traverse

GPU Allocator has worked great for Vulkan so far, so it is only natural to add support for D3D12. We managed to reuse all the sub-allocation logic from the Vulkan allocator. Both Vulkan and D3D12 will be behind feature flags, so the user can decide which API support they want to compile in there.

Todo:
* [ ] Clean-up visualizer code.
* [ ] Update README.md and lib.rs documentation.
* [ ] Should the D3D12 allocator take shared ownership over the device by using `AddRef` and `Release`?
* [ ] Remove todos.

2021-08-16 07:48 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +///
Docs?

2021-08-16 07:49 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    /// Alignment of allocation, should be queried using `ID3D12Device::GetResourceAllocationInfo`
```suggestion
    /// Size of allocation, should be queried using [`d3d12::ID3D12Device::GetResourceAllocationInfo()`]
    pub size: u64,
    /// Alignment of allocation, should be queried using [`d3d12::ID3D12Device::GetResourceAllocationInfo()`]
```
?

2021-08-16 07:50 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    /// Resource category based on resource dimension and flags. Can be created from a `D3D12_RESOURCE_DESC`
```suggestion
    /// Resource category based on resource dimension and flags. Can be created from a [`d3d12::D3D12_RESOURCE_DESC`]
```

2021-08-16 07:52 UTC, MarijnS95 commented on examples/d3d12-visualization/src/main.rs
> +    loop {
```suggestion
    for adapter_index in 0..
```

Drop the `+=` in multiple places below.

2021-08-16 07:54 UTC, MarijnS95 commented on examples/d3d12-buffer/src/main.rs
> +use log::*;
This example seems to use a mixture of `error!(...)`, `log!(Type, ...)` and `println!(...)`, can we clean that up?

2021-08-16 07:56 UTC, MarijnS95 commented on examples/d3d12-visualization/src/main.rs
> +            command_list
Drop `let` binding?

2021-08-16 07:58 UTC, MarijnS95 commented on examples/d3d12-visualization/src/main.rs
> +                queue.ExecuteCommandLists(1, lists.as_ptr());
Doesn't `&command_list as *const _ as *const *mut ID3D12CommandList` work directly here? Or `&command_list as &*mut ID3D12CommandList as *const _`?

2021-08-16 07:59 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +            != 0
Didn't these types have `.contains`/`.intersects`?

2021-08-16 08:02 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    /// for this reason. Keep in mind to also pass `Self::offset()` along to it.
Could use a bunch of `[]` intradoc-links, pointing users to the right bits in the winapi documentation.

2021-08-16 08:03 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    #[cfg(feature = "winapi")]
Interesting, and good choice if `windows-rs` becomes a thing with a sharable public API at some point; but for now moot since the below uses `winapi` a whole lot without being limited to this feature toggle.

2021-08-16 08:06 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                .ok_or_else(|| AllocationError::Internal("Failed to create ID3D12Heap".into()))?
Might as well add `AllocationError::OOM`?

2021-08-16 08:10 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +#[cfg(windows)]
This and the other two occurrences in this file are already implied by `mod d3d12` being loaded in the first place?

2021-08-16 08:10 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +            }
`find`?

2021-08-16 08:11 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +            }
I think there exists a `let block_index = self.memory_blocks.iter().position(|block| block.is_none());` for exactly this purpose, too.

2021-08-16 08:16 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                .ok_or_else(|| AllocationError::Internal("Failed to create ID3D12Heap".into()))?
https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createheap#return-value

Maybe only do this if the resultcode is `E_OUTOFMEMORY`?

2021-08-16 08:16 UTC, max-traverse commented on src/d3d12/mod.rs
> +            != 0
These flags don't as this is a u32 type, but the DXGI flags seem to support it.

2021-08-16 08:17 UTC, max-traverse commented on src/d3d12/mod.rs
> +            != 0
oh nevermind, my rust-analyzer is being slow, DXGI doesn't support it either.

2021-08-16 08:21 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                log!(Level::Debug, "Free stack trace: {}", backtrace);
Just use `{:?}` in the `log!()`?

2021-08-16 11:11 UTC, max-traverse commented on src/d3d12/mod.rs
> +                .ok_or_else(|| AllocationError::Internal("Failed to create ID3D12Heap".into()))?
I handle `E_OUTOFMEMORY` as an `OutOfMemory` error. All other errors are now internal errors (including the pointer being null, which shouldn't happen if the `HRESULT` was `S_OK`.

2021-08-16 11:22 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                    "ID3D12Device::CreateHeap failed with hr 0x{:x}",
```suggestion
                    "ID3D12Device::CreateHeap failed with hr {:#x}",
```
?

2021-08-16 11:48 UTC, max-traverse commented on src/d3d12/mod.rs
> +                    "ID3D12Device::CreateHeap failed with hr 0x{:x}",
Ah I didn't know about that one.

2021-08-16 11:49 UTC, max-traverse commented on examples/d3d12-buffer/src/main.rs
> +use log::*;
I made everything use `error!` and `info!` in this example.

2021-08-18 11:57 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    pub unsafe fn heap(&self) -> *mut d3d12::ID3D12Heap {
Does this need to be unsafe, per the guidelines we set up prior?

2021-08-18 11:57 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +        let heap = unsafe {
Only calling `CreateHeap` is unsafe here (unless I missed something. Let's try to minimize the code surface inside `unsafe {}`.

2021-08-18 11:57 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                device.CreateHeap(&desc, &d3d12::IID_ID3D12Heap, &mut heap as *mut _ as *mut _);
In Breda we migrated to:

```suggestion
            let mut heap = std::ptr::null_mut();

            let hr =
                device.CreateHeap(&desc, &d3d12::IID_ID3D12Heap, &mut heap);
            let heap = : heap.cast::<d3d12::ID3D12Heap>();
```

Thoughts?

2021-08-18 12:10 UTC, MarijnS95 requested changes

2021-08-18 12:10 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +                    },
FWIW:
```suggestion
                    Err(AllocationError::OutOfMemory) => {} // Block is full, continue search.
                    Err(err) => return Err(err),            // Unhandled error, return.
```

2021-08-18 12:10 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +            },
Nested `match` block can be collapsed too, just like above.

2021-08-18 12:11 UTC, MarijnS95 commented on src/vulkan/mod.rs
> +use log::{debug, warn, Level};
I pushed "global" changes to Vulkan to this branch as well; shall I PR them separately later?

2021-08-23 08:32 UTC, max-traverse commented on src/vulkan/mod.rs
> +use log::{debug, warn, Level};
It's probably best to PR this separately. This PR is already huge, so let's try to not let it get bigger.

2021-08-23 08:37 UTC, MarijnS95 commented on src/vulkan/mod.rs
> +use log::{debug, warn, Level};
Should all be pushed off in the last force-push, let's get this done :)

2021-08-23 08:40 UTC, max-traverse commented on src/d3d12/mod.rs
> +    pub unsafe fn heap(&self) -> *mut d3d12::ID3D12Heap {
I made it unsafe since the vulkan equivalent is also unsafe in this library. If it should be safe I think that should happen in a different PR.

2021-08-23 08:50 UTC, max-traverse commented on examples/d3d12-visualization/src/main.rs
> +                queue.ExecuteCommandLists(1, lists.as_ptr());
I have actually come to prefer the array method (although the hardcoded 1 should be replaced). It makes it simple to add more elements later. In my mind, it also represents more how the API is supposed to be used. You pass an array of things by pointer, even though that can be achieved by taking the address of the one element you have.

2021-08-23 09:02 UTC, MarijnS95 commented on examples/d3d12-visualization/src/main.rs
> +                queue.ExecuteCommandLists(1, lists.as_ptr());
> although the hardcoded 1 should be replaced

Yeah that's my main gripe otherwise; looks like there's one case remaining where `.len()` should be used. You're free to remve `[*mut ID3D12CommandList; 1]` though, the cast already fully defines the target type and the size is implicit.

2021-08-23 09:03 UTC, Jasper-Bekkers commented on src/d3d12/mod.rs
> +    #[cfg(feature = "winapi")]
Worst case we can just pass around a `*const ()` instead - loses type safety but in return we get interoperability with both crates.

2021-08-23 09:09 UTC, MarijnS95 commented on src/d3d12/mod.rs
> +    #[cfg(feature = "winapi")]
Fine to stick with winapi for now and drop this `#[cfg()]` (otherwise you'd have to spread around at least a couple dozen since it's used _everywhere_ in the public API). We'll see later if we:

- Convert the internals to windows-rs for simpler, safer, and more convenient code;
- Stick to winapi ptrs to convert to/from;
- Have a mode (feature) where our API just exposes (`type`def'd) raw pointers and not have any winapi dependency at all.

Until windows-rs comes with a shareable crate that exposes d3d12 types for interoperability between libraries.

2021-08-23 09:42 UTC, MarijnS95 approved these changes
Apart one stray `#[cfg(feature = "winapi")]` (see the remaining open comment), this seems okay to get in right now!

2021-08-23 09:48 UTC, max-traverse commented on src/d3d12/mod.rs
> +    #[cfg(feature = "winapi")]
Yeah I think for now using `winapi` should be fine. Once `windows-rs` is in a stable state we can look into switching to that.

2021-08-23 09:55 UTC, MarijnS95 approved these changes

2021-08-23 09:55 UTC, max-traverse commented
Stray `#[cfg(feature = "winapi")]` has been removed and my checklist has been finished except for restructuring the visualizer a bit. I'll do that in another PR so we can get this huge PR merged.
Now just waiting for CI before merging.

2021-08-23 10:09 UTC, merged