Allocator visualizer
Traverse-Research/gpu-allocator pull request #7
Opened 2020-11-24 17:21 UTC by max-traverse

Introducing an optional feature: the allocator visualizer.
It's an imgui based UI that allows you to inspect where each allocation is ending up. It can even show the backtrace of each allocation that happened.
It also allows the user to inspect information about the different types of memory available on the GPU.

2020-11-24 21:47 UTC, Jasper-Bekkers requested changes
Good work! Good to see the visualizer out in the open now too. I think it's good to also add some screenshots of it to the README.md file.

2020-11-24 21:47 UTC, Jasper-Bekkers commented on examples/vulkan-visualization/src/main.rs
> +            let layer_names = [CString::new("VK_LAYER_KHRONOS_validation").unwrap()];
Validation layer should probably be optional / off by default since not everybody will have the VulkanSDK installed. (Or at least print out a message where to download the SDK if it fails).

2020-11-24 21:47 UTC, Jasper-Bekkers commented on examples/vulkan-visualization/src/main.rs
> +        )?;
Since we have so little code that actually demos the example it might be nicer to pull it out to a loose file and leave all the ash/vulkan extra code in a helper file (might be useful for some other examples later on too).

2020-11-24 21:47 UTC, Jasper-Bekkers commented on examples/vulkan-visualization/src/shaders/imgui.ps.hlsl
> +    //return input.color;
Nit: commented code.

2020-11-24 21:47 UTC, Jasper-Bekkers commented on examples/vulkan-visualization/src/shaders/imgui.vs.hlsl
> +    //o.position = float4(vertex.pos * float2(1.0 / 1920.0, 1.0 / 1080.0) + float2(0, 0), 0, 1);
Nit: commented code.

2020-11-24 21:47 UTC, Jasper-Bekkers commented on examples/vulkan-visualization/src/main.rs
> +            .unwrap();
It might be nicer to check in pre-compiled .spv binaries along with the shaders and just have a script that calls into dxc instead of using hassle. It's not expected that everybody has a copy of dxcompiler.dll on their system (that can compile SPIR-V code).

2020-11-30 12:47 UTC, max-traverse commented on examples/vulkan-visualization/src/main.rs
> +        )?;
I have moved the imgui renderer to a seperate file. I did the same for one of the helper functions, as it's shared between the example and the imgui renderer.

2020-12-08 14:08 UTC, merged