🤷‍♂️ Adding an `Option<&mut bool>` argument in the allocator imgui rendering
Traverse-Research/gpu-allocator pull request #83
Opened 2021-11-29 13:17 UTC by EmilioLaiso

This allows calling code to do the following:

- Pass None to just render the editor as usual
- Pass Some(&mut bool) to control if the window is rendered and get information in return regarding a request for closure of the window (user clicks X button on the imgui window).
This allows for easier integration with UI systems.

I had conversations with @MarijnS95 about this and we're still not 100% happy with the code, adding the draft PR because I need to reference it in another project :P

2021-11-29 18:59 UTC, MarijnS95 requested changes

2021-11-29 18:59 UTC, MarijnS95 commented on src/d3d12/visualizer.rs
> +        }
For general use, I think the precedent should be that you don't call this function if you don't want the UI to be rendered.

```suggestion
        if let Some(opened) = opened {
            window = window.opened(opened);
        }
```

2021-11-29 18:59 UTC, MarijnS95 commented on src/d3d12/visualizer.rs
> +        }
Then, given the comment above that we shouldn't call `render_main_window` if it's `Some(false)` (ie. the user/caller _explicitly_ - by passing `Some` - asks for this window to _not_ be shown) you can massively simplify this with:

```suggestion
        if opened != Some(&mut false) {
            self.render_main_window(ui, opened, allocator);
            self.render_memory_block_windows(ui, allocator);
        }
```

If the caller doesn't care about showing or hiding the window and passes `None` this code will always run (and as discussed offline, not calling `.opened()` causes the `x` button to remain hidden).

By the way, don't forget to add some doc-comments explaining this use :)

2021-11-30 13:46 UTC, MarijnS95 commented on src/d3d12/visualizer.rs
> +    ///  - If the bool is true the widget will be drawn and an (X) closing button will be added to the widget bar.
```suggestion
    /// Pass [`None`] if no control and readback information is required. This will always render the widget.
    /// When passing `Some(&mut bool)`:
    /// - If [`false`], the widget won't be drawn.
    /// - If [`true`], the widget will be drawn and an (X) closing button will be added to the widget bar.
```

2021-12-01 17:43 UTC, max-traverse commented
@EmilioLaiso Are there still changes you want to make to this since it's a draft, or can we merge this?

2021-12-01 22:08 UTC, MarijnS95 commented
@EmilioLaiso you can also apply the doc-comment change to the other documentation in this PR :)

2021-12-02 10:08 UTC, MarijnS95 commented on src/vulkan/visualizer.rs
> +    /// The `Option<&mut bool>` can be used control and track changes to the opened/closed status of the widget.
```suggestion
    /// The [`Option<&mut bool>`] can be used control and track changes to the opened/closed status of the widget.
```

2021-12-02 10:08 UTC, MarijnS95 commented on src/d3d12/visualizer.rs
> +    /// The `Option<&mut bool>` can be used control and track changes to the opened/closed status of the widget.
```suggestion
    /// The [`Option<&mut bool>`] can be used control and track changes to the opened/closed status of the widget.
```

2021-12-02 10:08 UTC, MarijnS95 approved these changes

2021-12-02 14:40 UTC, merged